import fasthtml.common as fh
from pydantic import BaseModel
import modal
from textwrap import dedent
import httpx

class Testimonial(BaseModel):
    quote: str
    name: str
    role: str
    company: str

    def __ft__(self):
        return fh.Div(
            fh.Blockquote(fh.P(self.quote)),
            fh.H4(self.name),
            fh.P(f"{self.role}, {self.company}"),
        )

schema = """{
    "title": "Testimonial",
    "type": "object",
    "properties": {
        "quote": {
            "title": "Quote",
            "type": "string"
        },
        "name": {
            "title": "Name",
            "type": "string"
        },
        "role": {
            "title": "Role",
            "description": "The professional role of the individual giving the testimonial.",
            "type": "string"
        },
        "company": {
            "title": "Company",
            "description": "The name of the company where the individual works or which they represent.",
            "type": "string"
        }
    },
    "required": ["quote", "name", "role", "company"]
}
"""

prompt_template = dedent(
                                    """
                                <|system|> You are a world class marketing copywriter. You must write new testimonials for a product by replying VALID JSON that matches the schema below.
                                
                                ```json
                                {schema}
                                ```
                                
                                Be creative and write new testimonials that are unique and engaging.<|end|>
                                <|user|> Write testimonials about the TimeMaster 2049, a time-stopping watch. A small, undistinguishable watch that can stop and start time whenever you want it to. <|end|>
                                <|assistant|>
                                """)

# FastHTML app setup
fasthtml_app, rt = fh.fast_app(hdrs=(
    fh.Style("""
        .htmx-indicator {
            display: none;
        }
        .htmx-request .htmx-indicator {
            display: block;
        }
    """),
))

@rt("/")
def get():
    return fh.Titled('Infinite Fake Testimonials',
                  fh.Div(
                      fh.Div(id="testimonial-card"),  # The placeholder for the testimonial card
                      fh.Div("This testimonial is fake. The product, person and company do not exist. All were generated by AI.", style='color: red;'),
                      fh.Div(
                          fh.Button("Next", id="next-btn", hx_get="/page", hx_target="#testimonial-card", hx_indicator="#loading"),  # Use HTMX to fetch testimonials
                      ),
                      fh.Div("Loading...", id="loading", cls="htmx-indicator") # Loading indicator
                  ),
                  fh.Script('htmx.trigger("#next-btn", "click")')
                  )

@rt("/page")
async def get():
    async with httpx.AsyncClient() as client:
        response = await client.post(
            "https://aastroza--outlines-app-fastapi-app.modal.run/generate",
            json={"json_schema": schema.strip(), "prompt": prompt_template.format(schema=schema.strip())}
        )
        if response.status_code == 200:
            result = response.json()["result"]
            testimonial = Testimonial(**result)
            return testimonial
        else:
            return fh.Div("Error generating testimonial")

if __name__ == "__main__":  # if invoked with `python`, run locally
    fh.serve(app="fasthtml_app")
else:  # create a modal app, which can be imported in another file or used with modal commands as in README
    app = modal.App(name="fasthtml-app")

    # modal uses decorators to define infrastructure and deployments
    @app.function(  # here's where you can attach GPUs, define concurrency limits, etc.
        image=modal.Image.debian_slim().pip_install(
            "python-fasthtml"
        ),
        allow_concurrent_inputs=1000,  # async functions can handle multiple inputs
    )
    @modal.asgi_app()  # add this decorator to a function that returns your fastHTML app to make it deployable on Modal
    def serve():
        return fasthtml_app